# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet tool install --global coveralls.net
      - name: Restore dependencies
        run: dotnet restore ./src --verbosity m
      - name: Pack
        run: dotnet pack -c release ./src/MuninNode
      - name: Build
        run: dotnet build  --no-restore -c release ./src/MuninNode --no-restore
      - name: Test
        run: dotnet test --verbosity normal ./src/Tests/Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover