name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet tool install --global coveralls.net
      - name: Restore dependencies
        run: dotnet restore ./src --verbosity m
      - name: Pack
        run: dotnet pack -c release ./src/MuninNode
      - name: Build
        run: dotnet build  --no-restore -c release ./src/MuninNode --no-restore
      - name: Test
        run: dotnet test --verbosity normal ./src/Tests/Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover